### PR TITLE
HV controls changed

### PR DESCRIPTION
**Pull request by ekraegeloh**

### CODE REVIEW

**Comment by mgmarino** [comment]
@mjbales do you want to handle the merge/push to production server?

**Comment by mgmarino** [comment]
@stefan789 is now a member of @nEDM-TUM/interface-team

**Comment by mjbales** [comment]
Yeah I can try. Ok to handle that in an hour or so?

**Comment by ekraegeloh** [comment]
yeah till the end of the week is fine ;) I am a little sad not to be part of that fancy new team ;P

**Comment by mjbales** [comment]
Oh reeeeealllly? Want a new job? =D

**Comment by ekraegeloh** [comment]
Well let me figure out where to do my PhD and then maybe yes :P

**Pull request merged**
